apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: diaspomoney-rules
  namespace: diaspomoney
  labels:
    app: diaspomoney
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: diaspomoney.rules
    rules:
    # === RÈGLES D'APPLICATION ===
    - alert: DiaspoMoneyHighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: critical
        service: diaspomoney
      annotations:
        summary: "High error rate detected"
        description: "DiaspoMoney has a high error rate of {{ $value }} errors per second"
        runbook_url: "https://docs.diaspomoney.fr/runbooks/high-error-rate"

    - alert: DiaspoMoneyHighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: diaspomoney
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }}s"

    - alert: DiaspoMoneyLowThroughput
      expr: rate(http_requests_total[5m]) < 0.1
      for: 10m
      labels:
        severity: warning
        service: diaspomoney
      annotations:
        summary: "Low throughput detected"
        description: "Request rate is {{ $value }} requests per second"

    # === RÈGLES DE BASE DE DONNÉES ===
    - alert: MongoDBConnectionFailure
      expr: mongodb_up == 0
      for: 1m
      labels:
        severity: critical
        service: mongodb
      annotations:
        summary: "MongoDB connection failed"
        description: "MongoDB is not responding"

    - alert: MongoDBHighConnections
      expr: mongodb_connections_current > 80
      for: 5m
      labels:
        severity: warning
        service: mongodb
      annotations:
        summary: "MongoDB high connection count"
        description: "MongoDB has {{ $value }} active connections"

    - alert: MongoDBSlowQueries
      expr: rate(mongodb_op_latencies_seconds_sum[5m]) > 1
      for: 5m
      labels:
        severity: warning
        service: mongodb
      annotations:
        summary: "MongoDB slow queries detected"
        description: "MongoDB query latency is {{ $value }}s"

    # === RÈGLES REDIS ===
    - alert: RedisConnectionFailure
      expr: redis_up == 0
      for: 1m
      labels:
        severity: critical
        service: redis
      annotations:
        summary: "Redis connection failed"
        description: "Redis is not responding"

    - alert: RedisHighMemoryUsage
      expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
      for: 5m
      labels:
        severity: warning
        service: redis
      annotations:
        summary: "Redis high memory usage"
        description: "Redis memory usage is {{ $value }}%"

    - alert: RedisKeyExpiration
      expr: rate(redis_keyspace_expirations_total[5m]) > 1000
      for: 5m
      labels:
        severity: info
        service: redis
      annotations:
        summary: "High key expiration rate"
        description: "Redis key expiration rate is {{ $value }} keys/sec"

    # === RÈGLES KAFKA ===
    - alert: KafkaBrokerDown
      expr: kafka_broker_up == 0
      for: 1m
      labels:
        severity: critical
        service: kafka
      annotations:
        summary: "Kafka broker down"
        description: "Kafka broker {{ $labels.broker }} is down"

    - alert: KafkaHighLag
      expr: kafka_consumer_lag_sum > 10000
      for: 5m
      labels:
        severity: warning
        service: kafka
      annotations:
        summary: "Kafka consumer lag high"
        description: "Kafka consumer lag is {{ $value }} messages"

    - alert: KafkaTopicPartitionCount
      expr: kafka_topic_partitions > 100
      for: 5m
      labels:
        severity: info
        service: kafka
      annotations:
        summary: "High Kafka topic partition count"
        description: "Topic {{ $labels.topic }} has {{ $value }} partitions"

    # === RÈGLES DE SÉCURITÉ ===
    - alert: HighFailedLoginAttempts
      expr: rate(auth_logins_failed[5m]) > 10
      for: 2m
      labels:
        severity: critical
        service: auth
      annotations:
        summary: "High failed login attempts"
        description: "Failed login rate is {{ $value }} attempts/sec"

    - alert: SuspiciousActivity
      expr: rate(security_suspicious_events[5m]) > 5
      for: 1m
      labels:
        severity: critical
        service: security
      annotations:
        summary: "Suspicious activity detected"
        description: "Suspicious activity rate is {{ $value }} events/sec"

    - alert: PCIComplianceViolation
      expr: pci_compliance_violations_total > 0
      for: 0m
      labels:
        severity: critical
        service: pci
      annotations:
        summary: "PCI compliance violation"
        description: "PCI compliance violation detected"

    - alert: GDPRDataBreach
      expr: gdpr_data_breaches_total > 0
      for: 0m
      labels:
        severity: critical
        service: gdpr
      annotations:
        summary: "GDPR data breach detected"
        description: "GDPR data breach detected"

    # === RÈGLES DE TRANSACTIONS ===
    - alert: HighTransactionFailureRate
      expr: rate(transactions_failed[5m]) / rate(transactions_total[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
        service: transactions
      annotations:
        summary: "High transaction failure rate"
        description: "Transaction failure rate is {{ $value }}%"

    - alert: PaymentGatewayDown
      expr: payment_gateway_up == 0
      for: 1m
      labels:
        severity: critical
        service: payment
      annotations:
        summary: "Payment gateway down"
        description: "Payment gateway is not responding"

    - alert: HighPaymentAmount
      expr: payment_amount_sum > 100000
      for: 0m
      labels:
        severity: warning
        service: payment
      annotations:
        summary: "High payment amount detected"
        description: "Payment amount is {{ $value }} XOF"

    # === RÈGLES DE NOTIFICATIONS ===
    - alert: NotificationServiceDown
      expr: notification_service_up == 0
      for: 1m
      labels:
        severity: critical
        service: notifications
      annotations:
        summary: "Notification service down"
        description: "Notification service is not responding"

    - alert: HighNotificationFailureRate
      expr: rate(notifications_failed[5m]) / rate(notifications_total[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: notifications
      annotations:
        summary: "High notification failure rate"
        description: "Notification failure rate is {{ $value }}%"

    # === RÈGLES DE SYSTÈME ===
    - alert: HighCPUUsage
      expr: rate(process_cpu_seconds_total[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        service: system
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is {{ $value }}%"

    - alert: HighMemoryUsage
      expr: process_resident_memory_bytes / (1024*1024*1024) > 2
      for: 5m
      labels:
        severity: warning
        service: system
      annotations:
        summary: "High memory usage"
        description: "Memory usage is {{ $value }}GB"

    - alert: DiskSpaceLow
      expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
      for: 5m
      labels:
        severity: critical
        service: system
      annotations:
        summary: "Low disk space"
        description: "Disk space is {{ $value }}% available"

    # === RÈGLES DE SANTÉ ===
    - alert: HealthCheckFailure
      expr: health_check_status == 0
      for: 1m
      labels:
        severity: critical
        service: health
      annotations:
        summary: "Health check failed"
        description: "Application health check failed"

    - alert: ServiceUnavailable
      expr: up == 0
      for: 1m
      labels:
        severity: critical
        service: system
      annotations:
        summary: "Service unavailable"
        description: "Service {{ $labels.job }} is unavailable"
