apiVersion: v1
kind: Namespace
metadata:
  name: diaspomoney-prod
  labels:
    name: diaspomoney-prod
    environment: production
    tier: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: diaspomoney-prod-infra
  labels:
    name: diaspomoney-prod-infra
    environment: production
    tier: infrastructure
