services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7.0
    container_name: diaspomoney-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: diaspomoney123
      MONGO_INITDB_DATABASE: diaspomoney
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - diaspomoney-network

  # Interface d'administration MongoDB (optionnel)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: diaspomoney-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: diaspomoney123
      ME_CONFIG_MONGODB_URL: mongodb://admin:diaspomoney123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: diaspomoney123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - diaspomoney-network

  # Redis pour le cache (optionnel, pour les sessions et cache)
  redis:
    image: redis:7-alpine
    container_name: diaspomoney-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - diaspomoney-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  diaspomoney-network:
    driver: bridge
