services:
  app:
    build: ../
    container_name: diaspomoney-app
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      # Utilise le VRAI nom du container MongoDB
      - MONGODB_URI=mongodb://diaspomoney:supersecret@mongodb:27017/diaspomoney?authSource=admin
      - NEXTAUTH_URL=https://app.diaspomoney.fr
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - diaspomoney
    labels:
      # Configuration Traefik pour l'exposition
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.diaspomoney.fr`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

  mongodb:
    env_file:
      - ../.env
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: diaspomoney
      MONGO_INITDB_ROOT_USERNAME: diaspomoney
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - diaspomoney

volumes:
  mongodb_data:

networks:
  diaspomoney:
    driver: bridge
    name: diaspomoney
  traefik:
    external: true
