services:
  mongodb:
    env_file:
      - ../.env.local
      - ../.env
    image: mongo:7.0
    container_name: dev-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: diaspomoney
      MONGO_INITDB_ROOT_USERNAME: diaspomoney
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    volumes:
      - mongodb_data:/data/db
    networks:
      - diaspomoney

volumes:
  mongodb_data:

networks:
  diaspomoney:
    driver: bridge
    name: diaspomoney
