include:
  - compose.monitoring.yml

networks:
  traefik: {}

volumes:
  traefik_letsencrypt: {}
  traefik_logs: {}

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik
      - diaspomoney
    ports:
      - "80:80"
      - "443:443"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.metrics.address=:9100
      - --certificatesresolvers.le.acme.email=contact@diaspomoney.fr
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.network=diaspomoney
      - --providers.docker.exposedByDefault=false
      - --api.dashboard=true
      - --api.insecure=false
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=metrics
      - --log.level=INFO
      - --log.format=json
      - --log.filePath=/var/log/traefik/traefik.log
      - --accessLog.filePath=/var/log/traefik/access.log
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - traefik_logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - traefik_basicauth
    labels:
      - traefik.enable=true
        # Router vers le dashboard Traefik (api@internal)
      - traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.diaspomoney.fr`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls=true
      - traefik.http.routers.traefik-dashboard.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard.service=api@internal
        # Middlewares: IP whitelist puis BasicAuth
      - traefik.http.middlewares.dash-auth.basicauth.usersfile=/run/secrets/traefik_basicauth
      - traefik.http.routers.traefik-dashboard.middlewares=dash-auth

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - traefik
      - diaspomoney
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    expose:
      - "3000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=diaspomoney
      # Routage HTTPS (production)
      - traefik.http.routers.app.rule=Host(`app.diaspomoney.fr`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=3000
      # Redirection HTTP vers HTTPS
      - traefik.http.routers.app-http.rule=Host(`app.diaspomoney.fr`)
      - traefik.http.routers.app-http.entrypoints=web
      - traefik.http.routers.app-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # Sécurité (HSTS)
      - traefik.http.middlewares.sec.headers.stsSeconds=31536000
      - traefik.http.middlewares.sec.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.sec.headers.stsPreload=true
      - traefik.http.routers.app.middlewares=sec

secrets:
  traefik_basicauth:
    file: ./secrets/traefik.htpasswd
