services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    container_name: app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
    networks:
      - diaspomoney
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    ports:
      - "3000:3000"
