entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    redirect-to-https:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: noop@internal

    redirect-www:
      rule: "Host(`app.diaspomoney.fr`)"
      entryPoints: [web, websecure]
      middlewares: [redirect-www]
      service: noop@internal

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    redirect-www:
      redirectRegex:
        regex: "^https?://www\\.(.*)"
        replacement: "https://$1"
        permanent: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

log:
  level: DEBUG
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false

