entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":9100"

certificatesResolvers:
  le:
    acme:
      email: contact@diaspomoney.fr
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Configuration HTTP gérée par les labels Docker
# Les redirections sont maintenant gérées par les labels des services

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics

log:
  level: DEBUG
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "diaspomoney"
    exposedByDefault: false
